export enum ActionTypes  {
    INCREMENT = 'INCREMENT',
    USER_REGISTER = 'REGISTRATION/USER_REGISTER',
    SET_USERS = 'SET_USERS'
}

export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const SET_USERS = 'SET_USERS';
export const USER_REGISTER = 'REGISTRATION/USER_REGISTER';
export const USER_REGISTER_LOADING = 'REGISTRATION/USER_REGISTER_LOADING';
export const USER_REGISTER_ERROR = 'REGISTRATION/USER_REGISTER_ERROR';