export enum ActionTypes  {
    USER_REGISTER = 'REGISTRATION/USER_REGISTER',
    USER_REGISTER_LOADING = 'REGISTRATION/USER_REGISTER_LOADING',
    USER_REGISTER_ERROR = 'REGISTRATION/USER_REGISTER_ERROR',
    SET_USERS = 'SET_USERS',

}