export enum ActionTypes  {
    USER_REGISTER = 'REGISTRATION/USER_REGISTER',
    USER_REGISTER_ERROR = 'REGISTRATION/USER_REGISTER_ERROR',
    USER_REGISTER_STATUS = 'REGISTRATION/USER_REGISTER_STATUS',
   // SET_USERS = 'SET_USERS',

    SET_USER = "SET_USER",
    LOGOUT = "LOGOUT",
    LOGIN= "LOGIN",

    GET_PACKS = "PACKS/GET_PACKS",
    SET_PACKS = "PACKS/SET_PACKS",
    UPDATE_PACKS = "PACKS/UPDATE_PACKS",
    LOADING_PACKS = "PACKS/LOADING_PACKS",
    DELETE_PACKS = "PACKS/DELETE_PACKS"
}